# Generated by Django 5.2.8 on 2025-11-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('travel_date', models.CharField(max_length=100)),
                ('preferences', models.CharField(max_length=255)),
                ('extra', models.CharField(max_length=255)),
            ],
        ),
    ]
